### ISSUE TITLE
Expected ':' issue in IE v2.1.0 

### ISSUE THREAD

**Issue by EmilsK** [taoeffect/vue-script2#38]
Hi, 

I'm experiencing an `Expected ':'` error on IE11 that is happening on `vue-script2` plugin import. 

Works correctly when downgraded to the previous version (2.0.3).
Can you take a look at what's not correct there with the newest version? 

Thanks, 
Emīls

**Comment by taoeffect** [comment]
Hi Emils, if I had to guess, this is probably due to the newer JS features that are not being downgraded by babel because of the [`browserlist`](https://github.com/taoeffect/vue-script2/blob/master/package.json#L53) setting.

Nobody should be using IE11 these days. It is an outdated and [insecure](https://www.cvedetails.com/version/156607/Microsoft-Internet-Explorer-11.html) browser that is no longer receiving security updates.
